import "./globals.css";
import Provider from "./provider";
import { Header, Footer } from "@/app/components";

export const metadata = {
  title: "SwiftMart | CharlesMall2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
